import { styleTags, tags as t } from "@lezer/highlight"

export const jsonataHighlighting = styleTags({
  Name: t.variableName,
  Variable: t.special(t.variableName),
  String: t.string,
  Number: t.number,
  Boolean: t.bool,
  Null: t.null,
  Regex: t.regexp,
  Wildcard: t.special(t.punctuation),
  Descendant: t.special(t.punctuation),
  Parent: t.special(t.punctuation),
  Placeholder: t.special(t.punctuation),
  BlockComment: t.blockComment,
  "function and or in": t.keyword,
  ArithOp: t.arithmeticOperator,
  CompareOp: t.compareOperator,
  ConcatOp: t.operator,
  RangeOp: t.operator,
  ChainOp: t.operator,
  ElvisOp: t.operator,
  CoalesceOp: t.operator,
  AssignOp: t.definitionOperator,
  "? :": t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ", ;": t.separator,
  ". @ #": t.derefOperator,
})
